<?php 
    require "./Aluno.php";

    $alunos = [
        new Aluno("Cecília Ayla Larissa Ribeiro", 10, 9, 9),
        new Aluno("Vicente Vicente João Carvalho", 10, 10, 10),
        new Aluno("Aparecida Maya Vanessa Melo", 10, 5, 6),
        new Aluno("Cecília Mariah Lopes", 5, 10, 10),
        new Aluno("Maria Marina Maitê Fogaça", 1, 10, 1),
        new Aluno("Sônia Daiane Rodrigues", 1, 1, 10),
        new Aluno("José Victor Fogaça", 1, 10, 10),
        new Aluno("Joana Maitê Hadassa Baptista", 8, 10, 9),
        new Aluno("Luan João  Galvão", 5, 10, 8),
        new Aluno("Bruno João Luan Galvão", 10, 10, 7),
        new Aluno("Caroline Rita Milena Almada", 7, 5, 10),
        new Aluno("Marcelo Felipe Francisco Assunção", 9, 10, 6),
        new Aluno("Lucca Leonardo Marcos da Mata", 1, 10, 1),
        new Aluno("Isabelle Carla Moraes", 1, 10, 1),
        new Aluno("Geraldo Kauê Luiz Baptista", 10, 5, 10),
        new Aluno("Luís Vitor Severino Almeida", 1, 1, 10),
        new Aluno("Rebeca Tereza da Paz", 1, 10, 10),
        new Aluno("Martin Marcos Vinicius Renato Assis", 10, 6, 7),
        new Aluno("Erick Hugo Yago da Mota", 1, 10, 9),
        new Aluno("Regina Simone das Neves", 10, 8, 7),
        new Aluno("Catarina Sônia Souza", 10, 1, 4),
        new Aluno("Cláudia Cecília Pinto", 10, 6, 7),
        new Aluno("Victor Mário Aparício ", 10, 10, 7),
        new Aluno("Paulo Fábio Oliver Almada", 10, 1, 10),
        new Aluno("Luan Calebe Roberto Nogueira", 1, 1, 10),
        new Aluno("Carolina Elaine Melissa Nunes", 1, 10, 1),
        new Aluno("Raul Giovanni Cauê Pereira", 8, 10, 1),
        new Aluno("Márcia Isabella Laura Almada", 1, 10, 1),
        new Aluno("Aurora Rita Teixeira", 9, 10, 7),
        new Aluno("Malu Antonella Duarte", 1, 10, 1),
        new Aluno("Heloisa Andreia Rodrigues", 5, 6, 4),
        new Aluno("Cristiane Clara Fabiana da Rocha", 4, 10, 7),
        new Aluno("André Samuel Farias", 3, 10, 6),
        new Aluno("Ester Mariana Beatriz Nascimento", 1, 10, 1),
        new Aluno("Rebeca Mariana Gabriela Mendes", 7, 6, 10),
        new Aluno("Bento Hugo Ribeiro", 10, 1, 9),
        new Aluno("Bento Hugo Ribeiro", 1, 1, 10),
        new Aluno("Juliana Letícia Mendes", 1, 1, 10),
        new Aluno("Nair Cecília Baptista", 1, 10, 1),
        new Aluno("Larissa Nina Rocha", 10, 1, 8),
        new Aluno("Milena Giovana Sales", 10, 10, 10),
    ];
    echo json_encode($alunos);
?>
